### ISSUE TITLE
Potential typo in wiki (Initializing Window)

### ISSUE THREAD

**Issue by Shailosingh** [hyperdregon/SimpleWinAPI#2]
On the [Initializing Window ](https://github.com/hyperdregon/SimpleWinAPI/wiki/2.--API-Docs#initializing-window) section, the example given is:
`swapi_createwindow(L"window", 0, 0, 600, 600);`

If I am not mistaken, shouldn't it be:
`swapi_initwindow(L"My Window", 0, 0, 600, 600);`

According to your documentation and demo, `swapi_createwindow()` doesn't have arguments.

**Comment by hyperdregon** [comment]
Yes, it is true. I changed a bit the code, so we would have 3 functions. init_window, create_window, and show_window. There only was create_window and show_window, so it was a typo. Thanks a lot for noticing the typo!

**Comment by hyperdregon** [comment]
Now I'm going to remove the init_window function, and combine init_window with create_window, same as how it was before. Thanks again for opening this issue!
